### ISSUE TITLE
Build branches

### ISSUE THREAD

**Issue by salanki** [coreweave/utility-images#8]
We want to build branches and tag them with the commit id, so we get docker images built for branches and not just when we merge to master. Similar to how we do in many other repos, ie https://github.com/coreweave/concierge-render/blob/develop/.gitlab-ci.yml.

**Comment by brandonrjacobs** [comment]
@salanki like this: https://gitlab.com/coreweave/utility-images/-/jobs/2347502462 I build a pre-release image already if this is how you want it done? It has the branch and sha tagged.

**Comment by salanki** [comment]
Ok, sorry I didn't see a branch build for @wbrown's torch-base, that's why.

**Comment by brandonrjacobs** [comment]
It builds on changes so if the files hadn't changed in that directory it won't run so might just need a whitespace commit to get an image building. needs to rebase on master now though after I fixed the semantic-release (if it hasn't been yet).
