### ISSUE TITLE
Enhancement: Add pytorch image

### ISSUE THREAD

**Issue by todie** [coreweave/utility-images#9]
@wbrown any additional context or specific requests?

**Comment by wbrown** [comment]
We have a `pytorch-base` docker image that is used as a base for the finetune workflows, and the gooseai inference nodes, here: https://github.com/coreweave/utility-images/pull/6

We need this particular build in `utility-images` to be tagged and run on the mega-builder, and it needs to be a public image accessible from anyone.

We may need to fix the base image with some NVidia repo-foo.

**Comment by todie** [comment]
Roger that "one pytorch image hold the repository fails", coming right up 🍕

**Comment by todie** [comment]
I'm having misgivings about this issue actually belonging in this project. @brandonrjacobs set up a neat utility-image scoped mono-repo that has some pretty lightweight container builds with a bit of orchestration and I quite like it, however I'm struggling to balance the requirements of the pytorch builder with the other builders without making a raging mess of this mono-repo's architecture and stated goals.

The good news is that I've got pytorch building and configured kaniko-cache for this repository 🎉 the bad news:
* there's no elegant way to specify the runner tag for just one of the image directories in this repository which means all these tiny images are requesting chonky boi build servers by reason of association with pytorch
* kaniko's executor:debug image is a fucking nightmare to work with in gitlab. 
* It doesn't have a real shell environment, requires whitelisting of files you don't want nuked between stages
* It places it's busybox environment in `/busybox/` (where the only useful shell lives `/busybox/sh`). Gitlab expects a number of shells in the usual paths but not `/busybox/sh/` which 
* becomes a problem for gitlab's `after_script` blocks because kaniko tears down the filesystem when it's done with the build.

Anyways TLDR: transfering this issue and closing PR and moving pytorch to a dedicated repository because getting it to play nice with the other images in this repo is a lovecraftian mind-fuck and I'll never get back the hours I spent tracing why only `after_scripts` failed.

**Comment by salanki** [comment]
I do believe the pytorch base image is special enough to warrant it's own repo. This was my first thought when I saw your struggles with getting it into this repo. My thought is when you have something general, and you all of a sudden need to add a boatload of different config flags / special cases for one thing, you probably want to break that one thing out instead of turning the `utility-images` into a monster of a monorepo.
